version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: "dev"
    ports:
      - "7777:7777"
      - "7778:7778"
    environment:
      - PORT=7777
      - REDIS_URL="redis://redis:6379"
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
